apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: control-net          # change the name if you like
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
