apiVersion: v1
kind: Pod
metadata:
  name: gpu-debugger
spec:
  containers:
  - name: gpu-debugger
    image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:cuda-v1.5.0
    env:
    - name: HF_HOME
      value: /mnt/project/hf_cache
    resources:
      requests:
        cpu: "4"
        memory: "16Gi"
        nvidia.com/gpu: 1
      limits:
        cpu: "8"
        memory: "32Gi"
        nvidia.com/gpu: 1
    securityContext:
      runAsUser: 0
    command: ["/bin/bash","-c","sleep infinity"]
    volumeMounts:
    - name: control-net
      mountPath: /mnt/project
  volumes:
  - name: control-net
    persistentVolumeClaim:
      claimName: control-net
  restartPolicy: Never
