apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synth-data          # change the name if you like
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
