apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controlnet-output
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
