apiVersion: v1
kind: Pod
metadata:
  name: data-debugger
spec:
  containers:
  - name: data-debugger
    image: gitlab-registry.nrp-nautilus.io/nrp/scientific-images/python:cuda-v1.5.0
    resources:
      requests:
        cpu: "4"
        memory: "16Gi"
        nvidia.com/gpu: 1
      limits:
        cpu: "8"
        memory: "32Gi"
        nvidia.com/gpu: 1
    securityContext:
      runAsUser: 0
    command: ["/bin/bash","-c","sleep infinity"]
    volumeMounts:
    - name: synth-data
      mountPath: /mnt/data
  volumes:
  - name: synth-data
    persistentVolumeClaim:
      claimName: synth-data
  restartPolicy: Never
